
#The trigger 'type' field should have the exact name that each trigger-class implements in it's interface.
#'record' field under each topic is used to enable/disable recording of that topic. By default, all topics are recorded, if this field is not present.

/robot/battery_state:
  msg_type: sensor_msgs/msg/BatteryState
  record: false
  triggers:
    - type: BatteryHealthTrigger
      persistance_duration: 5.0
      use_msg_stamp: true

/robot/pose:
  msg_type: geometry_msgs/msg/PoseStamped
  triggers:
    - type: ZoneTriggerWithPoseStamped
      persistance_duration: 3.0
      use_msg_stamp: false
      trigger_zone: {"min_x": 0.0, "max_x": 10.0, "min_y": 0.0, "max_y": 5.0, "min_z": 0, "max_z": 100.0}

/robot/fix:
  msg_type: sensor_msgs/msg/NavSatFix
  record: true
  triggers:
    - type: ZoneTriggerWithNavSatFix
      use_msg_stamp: true
      persistance_duration: 10.0
      trigger_zone: {"latitude_max": 34.55, "latitude_min": 34.15, "longitude_max": 122.55, "longitude_min": 122.15, "altitude_max": 100.0, "altitude_min": 10.0}
    - type: NavSatInvalidFixTrigger
      persistance_duration: 10.0
      use_msg_stamp: false

/robot/odometry:
  record: True
  msg_type: nav_msgs/msg/Odometry
