
#The trigger 'type' field should have the exact name that each trigger class maps as Trigger::name
#If you don't need a trigger, no need to recompile the code by changing the variant, just set the 'enabled' field here to false.

/robot/battery_state:
  msg_type: sensor_msgs/msg/BatteryState
  triggers:
    - type: BatteryStateTrigger
      enabled: true
      persistance_duration: 3.0
      use_msg_stamp: false

/robot/pose:
  msg_type: geometry_msgs/msg/PoseStamped
  triggers:
    - type: ZoneTriggerWithPoseStamped
      enabled: true
      persistance_duration: 10.0
      extra_args:
        trigger_zone: {"min_x": 0.0, "max_x": 10.0, "min_y": 0.0, "max_y": 5.0, "min_z": 0, "max_z": 100.0}

/robot/fix:
  msg_type: sensor_msgs/msg/NavSatFix
  trigger_info:
    - type: ZoneTriggerWithNavSatFix
      enabled: false
      persistance_duration: 15.0
      trigger_zone: {"latitude_max": 34.55, "latitude_min": 34.15, "longitude_max": 122.55, "longitude_min": 122.15, "altitude_max": 100.0, "altitude_min": 10.0}
    - type: NavSatInvalidFixTrigger
      enabled: true
      persistance_duration: 20.0
      use_msg_stamp: true